sonar.projectKey= <SEU_PROJETO_NO_SONARCLOUD>
sonar.organization=<SUA_ORGANIZAÇÂO>

sonar.sources=.  # path of analyzed code
sonar.exclusions= # ignored paths

sonar.tests= .
sonar.test.inclusions==**/*_test.go
sonar.go.coverage.reportPaths=coverage.out 
